variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository



image: openjdk

stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - rest-kotlin-quickstart/target/rest-kotlin-quickstart-1.0-SNAPSHOT.jar

production:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo $SSH_MIKRUS >> ~/.ssh/id_rsa.pub
    - ssh root@srv04.mikr.us -p10569 "cd ~; touch test.txt"
  #    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  #    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
  #    - ./cf push
  only:
    - master